server:
  port: 6001

spring:
  application:
    name: net_trip_getway
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.123.162:8848 #配置Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true       #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: wechat_service #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:5001          #匹配后提供服务的路由地址
          uri: lb://wechatService                  #配置nacos里面的服务名
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由
